### ISSUE TITLE
Change all `print(...)` to `logger` calls

### ISSUE THREAD

**Issue by Athanasius** [tezw21/BGS-Tally-v2.0#1]
Now I've started using BGS Tally the way it just uses `print(...)`, rather than the EDMC logging, is annoying me.  Especially when I'm doing main EDMC development !

Please read https://github.com/EDCD/EDMarketConnector/blob/main/PLUGINS.md#logging for the details, which will be a small bit of code in `load.py` to ensure logging is set up, and then changing each `print(...)` to either `logger.info(...)` or another appropriate logging level function.

**Comment by tezw21** [comment]
Print statements removed as no longer used
